url validation done

diff --git a/5-Mini-Gobuster/mini_Gobuster b/5-Mini-Gobuster/mini_Gobuster
--- a/5-Mini-Gobuster/mini_Gobuster
+++ b/5-Mini-Gobuster/mini_Gobuster
@@ -10,19 +10,23 @@ filtering(){
 	fi
 }
 
-validating_flag_u(){
+validate_flag_u(){
+
+	if [[ ! "$1" =~ http://127.0.0.1:9000 ]] && [[ ! "$1" =~ https?://(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z0-9]{2,} ]] ; then
+		echo "Invalid Url! enter correct url"
+		exit 1
+	fi
+}
+
+validate_flag_w(){
+
+	echo "$1"
 
 }
 
-validating_flag_w(){
+validate_flag_c(){
 
-
-
-}
-
-validating_flag_c(){
-
-
+	echo "$1"
 }
 
 
@@ -102,6 +106,18 @@ do
 	esac
 done
 
-validate_flag_u "$u_give" "$url"
-validate_flag_w "$w_give" "$wordlist"
+if [[ ! "$u_give" = true ]]; then
+
+	echo "./mini_Gobuster: option requires an argument -- u"
+	exit 1
+
+fi
+if [[ ! "$w_give" = true ]]; then
+
+	echo "./mini_Gobuster: option requires an argument -- w"
+	exit
+fi
+
+validate_flag_u "$url"
+validate_flag_w "$wordlist"
 validate_flag_c "$c_give" "$filter_status"
